### PR TITLE
Created Readme.md

### PR DESCRIPTION
**Pull request by HragA**

### CODE REVIEW

**Comment by StrangeOne101** [comment]
Hey, looks pretty good. Could you add the gif from the overview page underneath the description and also copy over the basic license section I have from the other readme I provided?

Cheers

**Comment by HragA** [comment]
Hi, 
Yeah I can add it give me couple minutes

**Comment by HragA** [comment]
Done

**Comment by StrangeOne101** [comment]
Excellent, exactly what I was after.

Merged. Cheers

**Pull request merged**
